unit KeyboardHook;

interface

uses
  Winapi.Windows,
  Winapi.Messages,
  Winapi.PsAPI,
  System.StrUtils,
  System.SysUtils,
  EngineState,
  SendInputHelper,
  Logger;

type
  TOnKeyChar = procedure(const AChar: string) of object;

procedure InstallKeyboardHook;
procedure RemoveKeyboardHook;
procedure SetKeyHandler(AHandler: TOnKeyChar);
procedure SetTargetProcessName(const AProcessName: string);
procedure SetAllowedProcessNames(const AProcessNames: string);

implementation

{ ==================================================
  EXPLICIT WinAPI STRUCT (BULLETPROOF)
  ================================================== }

type
  PKBDLLHookStruct = ^TKBDLLHookStruct;
  TKBDLLHookStruct = record
    vkCode: DWORD;
    scanCode: DWORD;
    flags: DWORD;
    time: DWORD;
    dwExtraInfo: ULONG_PTR;
  end;

var
  KBHook: HHOOK = 0;
  KeyHandler: TOnKeyChar = nil;
  TargetProcessName: string = '';
  AllowedProcessNames: string = '';

const
  PROCESS_QUERY_LIMITED_INFORMATION = $1000;

  // KBDLLHOOKSTRUCT.flags bit indicating the event was generated by
  // SendInput/keybd_event (ours or anyone else's) rather than real hardware.
  LLKHF_INJECTED = $10;

{ --------------------------------------------------
  Convert Virtual Key to Unicode character
-------------------------------------------------- }
function VKToChar(vkCode: DWORD; scanCode: DWORD): string;
var
  KeyboardState: TKeyboardState;
  WideBuf: array[0..3] of WideChar;
  Len: Integer;
begin
  Result := '';

  FillChar(KeyboardState, SizeOf(KeyboardState), 0);

  if GetAsyncKeyState(VK_SHIFT) < 0 then
    KeyboardState[VK_SHIFT] := $80;
  if GetAsyncKeyState(VK_LSHIFT) < 0 then
    KeyboardState[VK_LSHIFT] := $80;
  if GetAsyncKeyState(VK_RSHIFT) < 0 then
    KeyboardState[VK_RSHIFT] := $80;
  if GetAsyncKeyState(VK_CONTROL) < 0 then
    KeyboardState[VK_CONTROL] := $80;
  if GetAsyncKeyState(VK_LCONTROL) < 0 then
    KeyboardState[VK_LCONTROL] := $80;
  if GetAsyncKeyState(VK_RCONTROL) < 0 then
    KeyboardState[VK_RCONTROL] := $80;
  if GetAsyncKeyState(VK_MENU) < 0 then
    KeyboardState[VK_MENU] := $80;
  if GetAsyncKeyState(VK_LMENU) < 0 then
    KeyboardState[VK_LMENU] := $80;
  if GetAsyncKeyState(VK_RMENU) < 0 then
    KeyboardState[VK_RMENU] := $80;
  if GetKeyState(VK_CAPITAL) > 0 then
    KeyboardState[VK_CAPITAL] := 1;

  Len := ToUnicode(
    vkCode,
    scanCode,
    KeyboardState,
    WideBuf,
    Length(WideBuf),
    0
  );

  // Handle surrogate pairs (Len can be 2 for SMP characters)
  if Len = 1 then
    Result := WideBuf[0]
  else if Len > 1 then
    SetString(Result, PWideChar(@WideBuf[0]), Len);
end;

function GetForegroundProcessName: string;
var
  ForegroundWnd: HWND;
  ProcessId: DWORD;
  ProcessHandle: THandle;
  Buffer: array[0..MAX_PATH - 1] of Char;
  Len: DWORD;
begin
  Result := '';
  ForegroundWnd := GetForegroundWindow;
  if ForegroundWnd = 0 then
    Exit;

  GetWindowThreadProcessId(ForegroundWnd, ProcessId);
  if ProcessId = 0 then
    Exit;

  ProcessHandle := OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, False, ProcessId);
  if ProcessHandle = 0 then
    Exit;

  try
    Len := GetModuleFileNameEx(ProcessHandle, 0, Buffer, Length(Buffer));
    if Len > 0 then
      Result := ExtractFileName(Buffer);
  finally
    CloseHandle(ProcessHandle);
  end;
end;

function GetForegroundWindowTitle: string;
var
  ForegroundWnd: HWND;
  Buffer: array[0..MAX_PATH - 1] of Char;
begin
  Result := '';
  ForegroundWnd := GetForegroundWindow;
  if ForegroundWnd = 0 then
    Exit;
  if GetWindowText(ForegroundWnd, Buffer, Length(Buffer)) > 0 then
    Result := Buffer;
end;

function IsModifierComboActive: Boolean;
begin
  // Use GetAsyncKeyState (physical state), matching VKToChar. GetKeyState reads
  // this thread's message queue, which an LL hook does not receive in step with
  // the current keystroke, so modifier state can lag and a Ctrl/Alt/Win shortcut
  // can be eaten by the hook (wrong-glyph injection instead of the shortcut).
  Result :=
    (GetAsyncKeyState(VK_CONTROL) < 0) or
    (GetAsyncKeyState(VK_MENU) < 0) or
    (GetAsyncKeyState(VK_LWIN) < 0) or
    (GetAsyncKeyState(VK_RWIN) < 0);
end;

function IsProcessAllowed(const ProcessName: string): Boolean;
var
  Names: TArray<string>;
  Name: string;
begin
  Result := False;
  if Trim(AllowedProcessNames) = '' then
    Exit(False);
  Names := AllowedProcessNames.Split([',', ';', #13, #10]);
  for Name in Names do
    if SameText(Trim(Name), ProcessName) then
      Exit(True);
end;

function IsTargetAppActive: Boolean;
var
  ActiveProcessName: string;
begin
  ActiveProcessName := GetForegroundProcessName;
  Result := IsProcessAllowed(ActiveProcessName) or
    ((TargetProcessName <> '') and SameText(ActiveProcessName, TargetProcessName));
end;

{ --------------------------------------------------
  Low-level keyboard hook procedure
-------------------------------------------------- }
function LowLevelKeyboardProc(
  nCode: Integer;
  wParam: WPARAM;
  lParam: LPARAM
): LRESULT; stdcall;
var
  KBD: PKBDLLHookStruct;
  Ch: string;
begin
  // If Windows says ignore, pass it on
  if nCode <> HC_ACTION then
    Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));

  KBD := PKBDLLHookStruct(lParam);

  try

  // Never reprocess our own (or anyone else's) synthetic key events. Every
  // key we inject below (SendVirtualKey/SendBackspace/SendUnicodeText) comes
  // back through this same global hook; without this check, injecting a
  // real VK_TAB/VK_RETURN/VK_BACK to "pass a key through" feeds it straight
  // back into the handler that injected it, forever.
  if (KBD.flags and LLKHF_INJECTED) <> 0 then
    Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));

  if not EngineEnabled then
    Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));

  // Fail open: if no layout is active (e.g. loading failed at startup),
  // don't intercept and discard keystrokes — let them through untouched.
  if not EngineHasActiveLayout then
    Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));

  if not IsTargetAppActive then
    Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));

  // Fail open: if our own injection is failing (e.g. UIPI blocks targeting a
  // window at a higher integrity level), stop consuming keys so the user's
  // typing is not silently eaten.
  if not InjectionOK then
    Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));

  if (wParam <> WM_KEYDOWN) and (wParam <> WM_SYSKEYDOWN) then
    Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));

  // Ignore modifier & control keys
  case KBD.vkCode of
    VK_SHIFT, VK_LSHIFT, VK_RSHIFT,
    VK_CONTROL, VK_LCONTROL, VK_RCONTROL,
    VK_MENU, VK_LMENU, VK_RMENU,
    VK_CAPITAL, VK_ESCAPE:
      Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));
  end;

  // Let Ctrl/Alt/Win combos (app shortcuts) pass through untouched.
  // Shift alone must still reach the engine because layouts use it for shifted keys.
  if IsModifierComboActive then
    Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));

  if (KBD.vkCode = VK_TAB) or (KBD.vkCode = VK_RETURN) then
  begin
    if Assigned(KeyHandler) then
    begin
      if KBD.vkCode = VK_TAB then
        KeyHandler(#9)
      else
        KeyHandler(#13);
    end;

    if KBD.vkCode = VK_TAB then
      SendVirtualKey(VK_TAB)
    else
      SendVirtualKey(VK_RETURN);

    Result := 1;
    Exit;
  end;

  // Handle BACKSPACE explicitly
  if KBD.vkCode = VK_BACK then
  begin
    if Assigned(KeyHandler) then
    begin
      KeyHandler(#8);  // ASCII Backspace
      Result := 1;     // BLOCK original
      Exit;
    end;
  end;

  // Convert VK → Unicode char
  Ch := VKToChar(KBD.vkCode, KBD.scanCode);
  if Ch = '' then
    Exit(CallNextHookEx(KBHook, nCode, wParam, lParam));

  // Pass to engine
  if Assigned(KeyHandler) then
  begin
    KeyHandler(Ch);

    // 🔴 BLOCK original keystroke
    Result := 1;
    Exit;
  end;

  Result := CallNextHookEx(KBHook, nCode, wParam, lParam);
  except
    on E: Exception do
    begin
      LogError('LowLevelKeyboardProc failed: ' + E.Message);
      Result := CallNextHookEx(KBHook, nCode, wParam, lParam);
    end;
  end;
end;

{ --------------------------------------------------
  Public API
-------------------------------------------------- }

procedure SetKeyHandler(AHandler: TOnKeyChar);
begin
  KeyHandler := AHandler;
end;

procedure SetTargetProcessName(const AProcessName: string);
begin
  TargetProcessName := Trim(AProcessName);
end;

procedure SetAllowedProcessNames(const AProcessNames: string);
begin
  AllowedProcessNames := Trim(AProcessNames);
end;

procedure InstallKeyboardHook;
begin
  if KBHook <> 0 then
    Exit;

  LogInfo('Installing keyboard hook');
  KBHook := SetWindowsHookEx(
    WH_KEYBOARD_LL,
    @LowLevelKeyboardProc,
    HInstance,
    0
  );

  if KBHook = 0 then
  begin
    LogError('Keyboard hook installation failed');
    RaiseLastOSError;
  end;
end;

procedure RemoveKeyboardHook;
begin
  if KBHook <> 0 then
  begin
    LogInfo('Removing keyboard hook');
    UnhookWindowsHookEx(KBHook);
    KBHook := 0;
  end;
end;

end.